const DEFAULT_WIDTH = 200;
const DEFAULT_HEIGHT = 200;
const DEFAULT_MARK_COLOR = 'x';
const DEFAULT_EMPTY_COLOR = ' ';
const DEFAULT_HORIZONTAL_BORDER = '*';
const DEFAULT_VERTICAL_BORDER = '|';

module.exports = {
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT,
  DEFAULT_MARK_COLOR,
  DEFAULT_EMPTY_COLOR,
  DEFAULT_HORIZONTAL_BORDER,
  DEFAULT_VERTICAL_BORDER
};
